const gulp = require('gulp');
const rename = require('gulp-rename');
const fileInclude = require('gulp-file-include');
const htmlmin = require('gulp-htmlmin');
const plumber = require('gulp-plumber');

module.exports = function (config) {
  return gulp.src(config.src)
    .pipe(plumber())
    .pipe(fileInclude({
      indent: true
    }))
    .pipe(htmlmin({
      caseSensitive: true,
      collapseBooleanAttributes: true,
      collapseWhitespace: true,
      conservativeCollapse: true,
      html5: true,
      includeAutoGeneratedTags: true,
      preventAttributesEscaping: true,
      removeAttributeQuotes: true,
      removeComments: true,
      removeEmptyAttributes: true,
      removeScriptTypeAttributes: true,
      removeStyleLinkTypeAttributes: true,
      useShortDoctype: true
    }))
    .pipe(rename(config.name))
    .pipe(gulp.dest(config.dest));
};
